version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=movie_tracker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C10searchengine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=C10searchengine
    ports:
      - "5050:80"
